In [1]:
import cv2


C:\anaconda_new\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
C:\anaconda_new\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
C:\anaconda_new\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
im_1=cv2.imread("C:/Users/admin pc/Desktop/barbara_original_image.jpg",0)

In [4]:
im_1

array([[176, 199, 206, ...,  99, 102,  98],
       [174, 195, 199, ...,  93,  95,  95],
       [178, 193, 193, ...,  92,  92,  98],
       ...,
       [ 95,  96,  97, ..., 116, 114, 113],
       [ 95,  96,  97, ..., 113, 113, 113],
       [ 97,  98,  98, ..., 106, 109, 111]], dtype=uint8)

In [5]:
im_1.shape

(512, 512)

In [6]:
cv2.imshow('im_1',im_1)

In [7]:
#cv2.waitKey(0)

In [8]:
from skimage.transform import resize
im_3=resize(im_1,(100,100))

In [9]:
im_3.shape

(100, 100)

In [10]:
im_3

array([[0.7492549 , 0.7523498 , 0.68281569, ..., 0.37003922, 0.37949333,
        0.40047059],
       [0.75714039, 0.72152   , 0.69941961, ..., 0.37100392, 0.38051922,
        0.4163498 ],
       [0.77396078, 0.66967843, 0.71062745, ..., 0.38388235, 0.36047059,
        0.41631373],
       ...,
       [0.39497255, 0.39558431, 0.39607843, ..., 0.45564706, 0.48235294,
        0.45631373],
       [0.40004235, 0.40842196, 0.40784314, ..., 0.39027451, 0.44847059,
        0.44866353],
       [0.38454902, 0.38847059, 0.39121569, ..., 0.33788235, 0.40227451,
        0.43505882]])

In [11]:
cv2.imshow('im_3',im_3)

In [12]:
#cv2.waitKey(0)

In [13]:
im_2=im_3.flatten()

In [14]:
im_2

array([0.7492549 , 0.7523498 , 0.68281569, ..., 0.33788235, 0.40227451,
       0.43505882])

In [15]:
data=list(im_2)

In [16]:
data

[0.7492549019607839,
 0.7523498039215712,
 0.6828156862745067,
 0.654704313725496,
 0.2685490196078471,
 0.4334886274509739,
 0.46698039215686815,
 0.26543529411764627,
 0.37639215686274663,
 0.39571921568626944,
 0.598727843137255,
 0.33409568627451774,
 0.11776470588235297,
 0.18541176470588014,
 0.44379921568626884,
 0.6342619607843121,
 0.6897396078431363,
 0.7157411764705882,
 0.7010980392156867,
 0.6646274509803926,
 0.6097254901960789,
 0.5574494117647067,
 0.5309882352941178,
 0.5428235294117645,
 0.5887341176470582,
 0.6340894117647057,
 0.6302682352941178,
 0.550666666666668,
 0.4550996078431384,
 0.41797960784313715,
 0.398274509803922,
 0.5179607843137226,
 0.6356862745098041,
 0.6196078431372549,
 0.6274509803921569,
 0.6196078431372549,
 0.615686274509804,
 0.615686274509804,
 0.615686274509804,
 0.6185882352941174,
 0.6274509803921569,
 0.6235294117647059,
 0.6317647058823528,
 0.6231372549019614,
 0.41278431372549124,
 0.3407545098039214,
 0.3667450980392157,
 0.3829725

In [17]:
import random

In [18]:
k1=random.choice(data)

In [19]:
k1

0.38568000000000024

In [20]:
k2=random.choice(data)

In [21]:
k2

0.11838901960784305

In [22]:
import statistics

In [23]:
k011=0
k022=0
while k1!=k011 and k2!=k022:
    s1111=[]
    s2222=[]
    for i in data:
        y1=(i-k1)**2
        y2=(i-k2)**2
        s1111.append((y1,i))
        s2222.append((y2,i))
        #print(s2222)
    s000=[]
    for (a,b) in s1111:
        for (c,d) in s2222:
            if b==d:
                y=(a,c,b)
                s000.append(y)
    #print(s000)
    s11_11=[]
    s22_22=[]
    for (a,c,b) in s000:
        e=min(a,c)
        if e==a:
            s11_11.append(b)
        elif e==c:
            s22_22.append(b)
        else:
            pass
    #print(s11_11)
    s333=[]
    s444=[]
    k011=statistics.median(s11_11)
    k022=statistics.median(s22_22)
    k001=round(k011,3)
    k002=round(k022,3)
    p1=(s11_11,k001)
    p2=(s22_22,k002)
    s333.append(p1)
    s444.append(p2)
    print(s333)
    #print(k002)
    if k1==k001 and k2==k002:
        print(k1,k2)
        print(s333,s444)
        break
    else:
        k1=k001  
        k2=k002
            
#print ( k1 , k2)

[([0.7492549019607839, 0.7523498039215712, 0.6828156862745067, 0.654704313725496, 0.2685490196078471, 0.4334886274509739, 0.46698039215686815, 0.26543529411764627, 0.37639215686274663, 0.39571921568626944, 0.598727843137255, 0.33409568627451774, 0.44379921568626884, 0.6342619607843121, 0.6897396078431363, 0.7157411764705882, 0.7010980392156867, 0.6646274509803926, 0.6097254901960789, 0.5574494117647067, 0.5309882352941178, 0.5428235294117645, 0.5428235294117645, 0.5887341176470582, 0.6340894117647057, 0.6302682352941178, 0.550666666666668, 0.4550996078431384, 0.41797960784313715, 0.398274509803922, 0.5179607843137226, 0.6356862745098041, 0.6356862745098041, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.619607843137

[([0.7492549019607839, 0.7523498039215712, 0.6828156862745067, 0.654704313725496, 0.4334886274509739, 0.46698039215686815, 0.37639215686274663, 0.39571921568626944, 0.598727843137255, 0.44379921568626884, 0.6342619607843121, 0.6897396078431363, 0.7157411764705882, 0.7010980392156867, 0.6646274509803926, 0.6097254901960789, 0.5574494117647067, 0.5309882352941178, 0.5428235294117645, 0.5428235294117645, 0.5887341176470582, 0.6340894117647057, 0.6302682352941178, 0.550666666666668, 0.4550996078431384, 0.41797960784313715, 0.398274509803922, 0.5179607843137226, 0.6356862745098041, 0.6356862745098041, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6196078431372549, 0.6274509803921569, 0.6274509803921569, 0.62745098039215

In [24]:
s333

[([0.7492549019607839,
   0.7523498039215712,
   0.6828156862745067,
   0.654704313725496,
   0.4334886274509739,
   0.46698039215686815,
   0.37639215686274663,
   0.39571921568626944,
   0.598727843137255,
   0.44379921568626884,
   0.6342619607843121,
   0.6897396078431363,
   0.7157411764705882,
   0.7010980392156867,
   0.6646274509803926,
   0.6097254901960789,
   0.5574494117647067,
   0.5309882352941178,
   0.5428235294117645,
   0.5428235294117645,
   0.5887341176470582,
   0.6340894117647057,
   0.6302682352941178,
   0.550666666666668,
   0.4550996078431384,
   0.41797960784313715,
   0.398274509803922,
   0.5179607843137226,
   0.6356862745098041,
   0.6356862745098041,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.6196078431372549,
   0.61960

In [25]:
s3333=[]
for (a,b) in s333:
    for i in a:
        s3333.append(i)

In [26]:
s3333

[0.7492549019607839,
 0.7523498039215712,
 0.6828156862745067,
 0.654704313725496,
 0.4334886274509739,
 0.46698039215686815,
 0.37639215686274663,
 0.39571921568626944,
 0.598727843137255,
 0.44379921568626884,
 0.6342619607843121,
 0.6897396078431363,
 0.7157411764705882,
 0.7010980392156867,
 0.6646274509803926,
 0.6097254901960789,
 0.5574494117647067,
 0.5309882352941178,
 0.5428235294117645,
 0.5428235294117645,
 0.5887341176470582,
 0.6340894117647057,
 0.6302682352941178,
 0.550666666666668,
 0.4550996078431384,
 0.41797960784313715,
 0.398274509803922,
 0.5179607843137226,
 0.6356862745098041,
 0.6356862745098041,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.6196078431372549,
 0.627450980

In [27]:
for (a,b) in s333:
    a1=enumerate(a)
    print(list(a1))

[(0, 0.7492549019607839), (1, 0.7523498039215712), (2, 0.6828156862745067), (3, 0.654704313725496), (4, 0.4334886274509739), (5, 0.46698039215686815), (6, 0.37639215686274663), (7, 0.39571921568626944), (8, 0.598727843137255), (9, 0.44379921568626884), (10, 0.6342619607843121), (11, 0.6897396078431363), (12, 0.7157411764705882), (13, 0.7010980392156867), (14, 0.6646274509803926), (15, 0.6097254901960789), (16, 0.5574494117647067), (17, 0.5309882352941178), (18, 0.5428235294117645), (19, 0.5428235294117645), (20, 0.5887341176470582), (21, 0.6340894117647057), (22, 0.6302682352941178), (23, 0.550666666666668), (24, 0.4550996078431384), (25, 0.41797960784313715), (26, 0.398274509803922), (27, 0.5179607843137226), (28, 0.6356862745098041), (29, 0.6356862745098041), (30, 0.6196078431372549), (31, 0.6196078431372549), (32, 0.6196078431372549), (33, 0.6196078431372549), (34, 0.6196078431372549), (35, 0.6196078431372549), (36, 0.6196078431372549), (37, 0.6196078431372549), (38, 0.6196078431372

In [28]:
for (a,b) in s444:
    a2=enumerate(a)
    print(list(a2))

[(0, 0.2685490196078471), (1, 0.26543529411764627), (2, 0.33409568627451774), (3, 0.11776470588235297), (4, 0.18541176470588014), (5, 0.3407545098039214), (6, 0.3399921568627449), (7, 0.3134117647058822), (8, 0.3286572549019609), (9, 0.34609411764705944), (10, 0.22123294117647285), (11, 0.19739607843137347), (12, 0.3035294117647055), (13, 0.13741176470588337), (14, 0.17749019607842947), (15, 0.3224800000000003), (16, 0.2999764705882355), (17, 0.2898823529411764), (18, 0.30023529411764704), (19, 0.3130933333333325), (20, 0.32337254901960777), (21, 0.34531607843137246), (22, 0.29713411764705705), (23, 0.21682666666666667), (24, 0.2325192156862746), (25, 0.2788235294117648), (26, 0.2736470588235293), (27, 0.20855999999999977), (28, 0.19687215686274534), (29, 0.32995921568627556), (30, 0.33670588235294063), (31, 0.3461098039215674), (32, 0.33286274509804054), (33, 0.18981176470588182), (34, 0.2154117647058849), (35, 0.21072156862745037), (36, 0.2754196078431341), (37, 0.33011764705882407),

In [29]:
s444

[([0.2685490196078471,
   0.26543529411764627,
   0.33409568627451774,
   0.11776470588235297,
   0.18541176470588014,
   0.3407545098039214,
   0.3399921568627449,
   0.3134117647058822,
   0.3286572549019609,
   0.34609411764705944,
   0.22123294117647285,
   0.19739607843137347,
   0.3035294117647055,
   0.13741176470588337,
   0.17749019607842947,
   0.3224800000000003,
   0.2999764705882355,
   0.2898823529411764,
   0.30023529411764704,
   0.3130933333333325,
   0.32337254901960777,
   0.34531607843137246,
   0.29713411764705705,
   0.21682666666666667,
   0.2325192156862746,
   0.2788235294117648,
   0.2736470588235293,
   0.20855999999999977,
   0.19687215686274534,
   0.32995921568627556,
   0.33670588235294063,
   0.3461098039215674,
   0.33286274509804054,
   0.18981176470588182,
   0.2154117647058849,
   0.21072156862745037,
   0.2754196078431341,
   0.33011764705882407,
   0.28721568627451033,
   0.25098039215686296,
   0.22101960784313773,
   0.19749019607843157,
   0.175

In [30]:
s4444=[]
for (a,b) in s444:
    for i in a:
        s4444.append(i)

In [31]:
s4444

[0.2685490196078471,
 0.26543529411764627,
 0.33409568627451774,
 0.11776470588235297,
 0.18541176470588014,
 0.3407545098039214,
 0.3399921568627449,
 0.3134117647058822,
 0.3286572549019609,
 0.34609411764705944,
 0.22123294117647285,
 0.19739607843137347,
 0.3035294117647055,
 0.13741176470588337,
 0.17749019607842947,
 0.3224800000000003,
 0.2999764705882355,
 0.2898823529411764,
 0.30023529411764704,
 0.3130933333333325,
 0.32337254901960777,
 0.34531607843137246,
 0.29713411764705705,
 0.21682666666666667,
 0.2325192156862746,
 0.2788235294117648,
 0.2736470588235293,
 0.20855999999999977,
 0.19687215686274534,
 0.32995921568627556,
 0.33670588235294063,
 0.3461098039215674,
 0.33286274509804054,
 0.18981176470588182,
 0.2154117647058849,
 0.21072156862745037,
 0.2754196078431341,
 0.33011764705882407,
 0.28721568627451033,
 0.25098039215686296,
 0.22101960784313773,
 0.19749019607843157,
 0.17584313725490217,
 0.1588235294117647,
 0.156078431372549,
 0.16282352941176442,
 0.1873

In [32]:
for x,y  in enumerate(data):
    for (a,b) in s333:
        for i in a:
            if y==i:
                data[x]=b
            else:
                pass
                
            

In [33]:
data

[0.6,
 0.6,
 0.6,
 0.6,
 0.2685490196078471,
 0.6,
 0.6,
 0.26543529411764627,
 0.6,
 0.6,
 0.6,
 0.33409568627451774,
 0.11776470588235297,
 0.18541176470588014,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.3407545098039214,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.3399921568627449,
 0.3134117647058822,
 0.3286572549019609,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.34609411764705944,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.22123294117647285,
 0.6,
 0.6,
 0.19739607843137347,
 0.3035294117647055,
 0.6,
 0.6,
 0.6,
 0.13741176470588337,
 0.17749019607842947,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.3224800

In [34]:
for x,y  in enumerate(data):
    for (a,b) in s444:
        for i in a:
            if y==i:
                data[x]=b
            else:
                pass

In [35]:
data

[0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.149,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0

In [36]:
data_1=data

In [37]:
data_1

[0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.6,
 0.6,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.149,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.149,
 0.149,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0

In [38]:
data_2=np.array(data_1)

In [39]:
data_2

array([0.6  , 0.6  , 0.6  , ..., 0.149, 0.6  , 0.6  ])

In [40]:
np.size(data_2)

10000

In [41]:
im_4=data_2.reshape((im_3.shape))

In [42]:
im_4

array([[0.6  , 0.6  , 0.6  , ..., 0.6  , 0.6  , 0.6  ],
       [0.6  , 0.6  , 0.6  , ..., 0.6  , 0.6  , 0.6  ],
       [0.6  , 0.6  , 0.6  , ..., 0.6  , 0.6  , 0.6  ],
       ...,
       [0.6  , 0.6  , 0.6  , ..., 0.6  , 0.6  , 0.6  ],
       [0.6  , 0.6  , 0.6  , ..., 0.6  , 0.6  , 0.6  ],
       [0.6  , 0.6  , 0.6  , ..., 0.149, 0.6  , 0.6  ]])

In [43]:
cv2.imshow('im_4',im_4)

In [46]:
#cv2.waitKey(0)