In [1]:
import cv2

C:\anaconda_new\lib\site-packages\numpy\core\__init__.py:29: UserWarning: loaded more than 1 DLL from .libs:
C:\anaconda_new\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
C:\anaconda_new\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
import numpy as np
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
im_1=cv2.imread("C:/Users/admin pc/Desktop/barbara_original_image.jpg",0)

In [5]:
im_1

array([[176, 199, 206, ...,  99, 102,  98],
       [174, 195, 199, ...,  93,  95,  95],
       [178, 193, 193, ...,  92,  92,  98],
       ...,
       [ 95,  96,  97, ..., 116, 114, 113],
       [ 95,  96,  97, ..., 113, 113, 113],
       [ 97,  98,  98, ..., 106, 109, 111]], dtype=uint8)

In [6]:
im_1.shape

(512, 512)

In [7]:
cv2.imshow('im_1',im_1)

In [8]:
#cv2.waitKey(0)

In [9]:
from skimage.transform import resize
im_3=resize(im_1,(100,100))

In [10]:
im_3.shape

(100, 100)

In [11]:
im_3

array([[0.7492549 , 0.7523498 , 0.68281569, ..., 0.37003922, 0.37949333,
        0.40047059],
       [0.75714039, 0.72152   , 0.69941961, ..., 0.37100392, 0.38051922,
        0.4163498 ],
       [0.77396078, 0.66967843, 0.71062745, ..., 0.38388235, 0.36047059,
        0.41631373],
       ...,
       [0.39497255, 0.39558431, 0.39607843, ..., 0.45564706, 0.48235294,
        0.45631373],
       [0.40004235, 0.40842196, 0.40784314, ..., 0.39027451, 0.44847059,
        0.44866353],
       [0.38454902, 0.38847059, 0.39121569, ..., 0.33788235, 0.40227451,
        0.43505882]])

In [12]:
im_3

array([[0.7492549 , 0.7523498 , 0.68281569, ..., 0.37003922, 0.37949333,
        0.40047059],
       [0.75714039, 0.72152   , 0.69941961, ..., 0.37100392, 0.38051922,
        0.4163498 ],
       [0.77396078, 0.66967843, 0.71062745, ..., 0.38388235, 0.36047059,
        0.41631373],
       ...,
       [0.39497255, 0.39558431, 0.39607843, ..., 0.45564706, 0.48235294,
        0.45631373],
       [0.40004235, 0.40842196, 0.40784314, ..., 0.39027451, 0.44847059,
        0.44866353],
       [0.38454902, 0.38847059, 0.39121569, ..., 0.33788235, 0.40227451,
        0.43505882]])

In [13]:
cv2.imshow('im_3',im_3)

In [14]:
#cv2.waitKey(0)

In [15]:
im_2=im_3.flatten()

In [16]:
im_2

array([0.7492549 , 0.7523498 , 0.68281569, ..., 0.33788235, 0.40227451,
       0.43505882])

In [17]:
data=list(im_2)

In [18]:
data

[0.7492549019607839,
 0.7523498039215712,
 0.6828156862745067,
 0.654704313725496,
 0.2685490196078471,
 0.4334886274509739,
 0.46698039215686815,
 0.26543529411764627,
 0.37639215686274663,
 0.39571921568626944,
 0.598727843137255,
 0.33409568627451774,
 0.11776470588235297,
 0.18541176470588014,
 0.44379921568626884,
 0.6342619607843121,
 0.6897396078431363,
 0.7157411764705882,
 0.7010980392156867,
 0.6646274509803926,
 0.6097254901960789,
 0.5574494117647067,
 0.5309882352941178,
 0.5428235294117645,
 0.5887341176470582,
 0.6340894117647057,
 0.6302682352941178,
 0.550666666666668,
 0.4550996078431384,
 0.41797960784313715,
 0.398274509803922,
 0.5179607843137226,
 0.6356862745098041,
 0.6196078431372549,
 0.6274509803921569,
 0.6196078431372549,
 0.615686274509804,
 0.615686274509804,
 0.615686274509804,
 0.6185882352941174,
 0.6274509803921569,
 0.6235294117647059,
 0.6317647058823528,
 0.6231372549019614,
 0.41278431372549124,
 0.3407545098039214,
 0.3667450980392157,
 0.3829725

In [19]:
data_1=[]
for i in data:
    y1=round(i,3)
    data_1.append(y1)


In [20]:
data_1

[0.749,
 0.752,
 0.683,
 0.655,
 0.269,
 0.433,
 0.467,
 0.265,
 0.376,
 0.396,
 0.599,
 0.334,
 0.118,
 0.185,
 0.444,
 0.634,
 0.69,
 0.716,
 0.701,
 0.665,
 0.61,
 0.557,
 0.531,
 0.543,
 0.589,
 0.634,
 0.63,
 0.551,
 0.455,
 0.418,
 0.398,
 0.518,
 0.636,
 0.62,
 0.627,
 0.62,
 0.616,
 0.616,
 0.616,
 0.619,
 0.627,
 0.624,
 0.632,
 0.623,
 0.413,
 0.341,
 0.367,
 0.383,
 0.392,
 0.392,
 0.396,
 0.388,
 0.38,
 0.379,
 0.383,
 0.388,
 0.458,
 0.772,
 0.748,
 0.81,
 0.837,
 0.723,
 0.529,
 0.54,
 0.568,
 0.529,
 0.612,
 0.641,
 0.585,
 0.514,
 0.496,
 0.478,
 0.428,
 0.495,
 0.54,
 0.513,
 0.412,
 0.34,
 0.313,
 0.329,
 0.434,
 0.563,
 0.525,
 0.402,
 0.381,
 0.402,
 0.409,
 0.424,
 0.395,
 0.387,
 0.394,
 0.357,
 0.346,
 0.358,
 0.395,
 0.381,
 0.382,
 0.37,
 0.379,
 0.4,
 0.757,
 0.722,
 0.699,
 0.589,
 0.221,
 0.43,
 0.466,
 0.197,
 0.304,
 0.384,
 0.746,
 0.464,
 0.137,
 0.177,
 0.407,
 0.549,
 0.55,
 0.553,
 0.574,
 0.591,
 0.591,
 0.574,
 0.533,
 0.476,
 0.418,
 0.367,
 0.322,

In [21]:
data_2=np.array(data_1)

In [22]:
data_2

array([0.749, 0.752, 0.683, ..., 0.338, 0.402, 0.435])

In [23]:
print(type(data_2))

<class 'numpy.ndarray'>


In [24]:
y1=max(data_2)

In [25]:
y1

0.902

In [26]:
y2=min(data_2)

In [27]:
y2

0.078

In [28]:
y3=np.mean(data_2)

In [29]:
y3

0.45644349999999995

In [30]:
s1=[]
s2=[]
for x in data_2:
    if x>=y2 and x<=y3:
        s1.append(x)
    elif x>y3 and x<=y1:
        s2.append(x)
    else:
        pass

In [31]:
s1

[0.269,
 0.433,
 0.265,
 0.376,
 0.396,
 0.334,
 0.118,
 0.185,
 0.444,
 0.455,
 0.418,
 0.398,
 0.413,
 0.341,
 0.367,
 0.383,
 0.392,
 0.392,
 0.396,
 0.388,
 0.38,
 0.379,
 0.383,
 0.388,
 0.428,
 0.412,
 0.34,
 0.313,
 0.329,
 0.434,
 0.402,
 0.381,
 0.402,
 0.409,
 0.424,
 0.395,
 0.387,
 0.394,
 0.357,
 0.346,
 0.358,
 0.395,
 0.381,
 0.382,
 0.37,
 0.379,
 0.4,
 0.221,
 0.43,
 0.197,
 0.304,
 0.384,
 0.137,
 0.177,
 0.407,
 0.418,
 0.367,
 0.322,
 0.3,
 0.29,
 0.3,
 0.313,
 0.411,
 0.323,
 0.345,
 0.371,
 0.391,
 0.4,
 0.396,
 0.384,
 0.384,
 0.384,
 0.388,
 0.388,
 0.297,
 0.217,
 0.233,
 0.279,
 0.274,
 0.209,
 0.197,
 0.33,
 0.417,
 0.407,
 0.401,
 0.414,
 0.407,
 0.366,
 0.337,
 0.346,
 0.333,
 0.388,
 0.383,
 0.369,
 0.371,
 0.381,
 0.416,
 0.19,
 0.438,
 0.215,
 0.211,
 0.275,
 0.379,
 0.437,
 0.421,
 0.375,
 0.33,
 0.287,
 0.251,
 0.221,
 0.197,
 0.176,
 0.159,
 0.156,
 0.163,
 0.187,
 0.274,
 0.426,
 0.326,
 0.337,
 0.355,
 0.382,
 0.396,
 0.392,
 0.384,
 0.381,
 0.388,


In [32]:
s2

[0.749,
 0.752,
 0.683,
 0.655,
 0.467,
 0.599,
 0.634,
 0.69,
 0.716,
 0.701,
 0.665,
 0.61,
 0.557,
 0.531,
 0.543,
 0.589,
 0.634,
 0.63,
 0.551,
 0.518,
 0.636,
 0.62,
 0.627,
 0.62,
 0.616,
 0.616,
 0.616,
 0.619,
 0.627,
 0.624,
 0.632,
 0.623,
 0.458,
 0.772,
 0.748,
 0.81,
 0.837,
 0.723,
 0.529,
 0.54,
 0.568,
 0.529,
 0.612,
 0.641,
 0.585,
 0.514,
 0.496,
 0.478,
 0.495,
 0.54,
 0.513,
 0.563,
 0.525,
 0.757,
 0.722,
 0.699,
 0.589,
 0.466,
 0.746,
 0.464,
 0.549,
 0.55,
 0.553,
 0.574,
 0.591,
 0.591,
 0.574,
 0.533,
 0.476,
 0.51,
 0.636,
 0.624,
 0.624,
 0.62,
 0.62,
 0.62,
 0.616,
 0.619,
 0.627,
 0.624,
 0.631,
 0.624,
 0.47,
 0.748,
 0.711,
 0.778,
 0.791,
 0.687,
 0.521,
 0.549,
 0.563,
 0.532,
 0.627,
 0.609,
 0.535,
 0.464,
 0.492,
 0.479,
 0.51,
 0.496,
 0.518,
 0.619,
 0.526,
 0.774,
 0.67,
 0.711,
 0.487,
 0.49,
 0.517,
 0.461,
 0.497,
 0.543,
 0.519,
 0.469,
 0.522,
 0.636,
 0.62,
 0.622,
 0.615,
 0.616,
 0.62,
 0.619,
 0.623,
 0.635,
 0.631,
 0.629,
 0.622,
 0.

In [33]:
s11=np.mean(s1)

In [34]:
s11

0.2903693239152371

In [35]:
s111=round(s11,3)

In [36]:
s111

0.29

In [37]:
s22=np.mean(s2)

In [38]:
s222=round(s22,3)

In [39]:
s222

0.62

In [40]:
for m in data_2:
    print(m)

0.749
0.752
0.683
0.655
0.269
0.433
0.467
0.265
0.376
0.396
0.599
0.334
0.118
0.185
0.444
0.634
0.69
0.716
0.701
0.665
0.61
0.557
0.531
0.543
0.589
0.634
0.63
0.551
0.455
0.418
0.398
0.518
0.636
0.62
0.627
0.62
0.616
0.616
0.616
0.619
0.627
0.624
0.632
0.623
0.413
0.341
0.367
0.383
0.392
0.392
0.396
0.388
0.38
0.379
0.383
0.388
0.458
0.772
0.748
0.81
0.837
0.723
0.529
0.54
0.568
0.529
0.612
0.641
0.585
0.514
0.496
0.478
0.428
0.495
0.54
0.513
0.412
0.34
0.313
0.329
0.434
0.563
0.525
0.402
0.381
0.402
0.409
0.424
0.395
0.387
0.394
0.357
0.346
0.358
0.395
0.381
0.382
0.37
0.379
0.4
0.757
0.722
0.699
0.589
0.221
0.43
0.466
0.197
0.304
0.384
0.746
0.464
0.137
0.177
0.407
0.549
0.55
0.553
0.574
0.591
0.591
0.574
0.533
0.476
0.418
0.367
0.322
0.3
0.29
0.3
0.313
0.51
0.636
0.624
0.624
0.62
0.62
0.62
0.616
0.619
0.627
0.624
0.631
0.624
0.411
0.323
0.345
0.371
0.391
0.4
0.396
0.384
0.384
0.384
0.388
0.388
0.47
0.748
0.711
0.778
0.791
0.687
0.521
0.549
0.563
0.532
0.627
0.609
0.535
0.464
0.492
0

0.386
0.337
0.553
0.396
0.158
0.208
0.43
0.569
0.476
0.56
0.649
0.694
0.721
0.737
0.752
0.753
0.757
0.765
0.765
0.765
0.769
0.775
0.781
0.792
0.796
0.796
0.8
0.804
0.808
0.804
0.804
0.8
0.797
0.701
0.661
0.651
0.713
0.716
0.723
0.682
0.651
0.647
0.612
0.475
0.451
0.463
0.534
0.633
0.536
0.359
0.271
0.261
0.296
0.328
0.31
0.242
0.133
0.11
0.11
0.188
0.394
0.414
0.429
0.332
0.366
0.403
0.398
0.224
0.19
0.309
0.584
0.642
0.625
0.593
0.57
0.157
0.177
0.205
0.239
0.352
0.494
0.584
0.397
0.277
0.322
0.378
0.459
0.517
0.541
0.623
0.732
0.659
0.546
0.648
0.644
0.468
0.238
0.16
0.242
0.377
0.333
0.413
0.549
0.287
0.149
0.224
0.44
0.643
0.649
0.681
0.731
0.749
0.753
0.758
0.765
0.769
0.769
0.773
0.774
0.782
0.785
0.793
0.797
0.796
0.797
0.8
0.804
0.808
0.804
0.804
0.803
0.8
0.8
0.717
0.655
0.616
0.702
0.728
0.701
0.645
0.629
0.656
0.659
0.552
0.5
0.513
0.59
0.628
0.424
0.239
0.222
0.288
0.36
0.362
0.297
0.216
0.144
0.114
0.115
0.256
0.394
0.403
0.39
0.289
0.313
0.356
0.266
0.184
0.208
0.283
0.54

0.473
0.516
0.595
0.86
0.884
0.843
0.84
0.843
0.843
0.839
0.843
0.822
0.755
0.631
0.612
0.616
0.605
0.596
0.608
0.604
0.607
0.604
0.598
0.589
0.588
0.588
0.596
0.607
0.611
0.624
0.691
0.739
0.726
0.702
0.686
0.707
0.734
0.724
0.603
0.597
0.712
0.706
0.651
0.626
0.611
0.665
0.661
0.602
0.513
0.423
0.358
0.318
0.255
0.219
0.188
0.204
0.255
0.213
0.158
0.202
0.365
0.297
0.218
0.351
0.54
0.753
0.645
0.472
0.303
0.267
0.309
0.417
0.557
0.646
0.666
0.682
0.82
0.824
0.828
0.831
0.831
0.838
0.839
0.839
0.831
0.746
0.458
0.365
0.361
0.353
0.364
0.406
0.576
0.487
0.414
0.48
0.5
0.469
0.385
0.443
0.456
0.523
0.571
0.713
0.774
0.81
0.814
0.819
0.823
0.823
0.814
0.741
0.647
0.545
0.606
0.612
0.604
0.604
0.6
0.609
0.612
0.606
0.6
0.604
0.608
0.612
0.616
0.632
0.639
0.693
0.779
0.774
0.766
0.746
0.714
0.691
0.711
0.725
0.688
0.565
0.61
0.677
0.655
0.62
0.597
0.553
0.533
0.483
0.419
0.347
0.279
0.227
0.231
0.341
0.394
0.311
0.208
0.141
0.149
0.303
0.527
0.46
0.384
0.394
0.612
0.773
0.637
0.487
0.339
0

0.489
0.484
0.461
0.441
0.507
0.485
0.442
0.45
0.496
0.526
0.491
0.417
0.176
0.149
0.165
0.359
0.597
0.608
0.604
0.599
0.596
0.583
0.58
0.584
0.591
0.591
0.644
0.694
0.706
0.679
0.644
0.593
0.54
0.463
0.412
0.379
0.358
0.329
0.251
0.218
0.175
0.178
0.171
0.178
0.219
0.293
0.362
0.396
0.443
0.481
0.456
0.418
0.386
0.383
0.395
0.349
0.376
0.363
0.361
0.401
0.435
0.449
0.449
0.46
0.468
0.476
0.405
0.33
0.432
0.603
0.665
0.666
0.627
0.58
0.558
0.553
0.587
0.622
0.592
0.584
0.609
0.522
0.517
0.698
0.822
0.854
0.859
0.863
0.859
0.86
0.863
0.86
0.859
0.866
0.867
0.847
0.771
0.613
0.507
0.479
0.479
0.49
0.448
0.433
0.488
0.48
0.441
0.455
0.488
0.504
0.446
0.323
0.153
0.149
0.161
0.359
0.607
0.615
0.608
0.607
0.596
0.591
0.589
0.59
0.588
0.587
0.642
0.683
0.687
0.663
0.638
0.58
0.515
0.423
0.36
0.328
0.315
0.286
0.245
0.257
0.201
0.179
0.174
0.157
0.15
0.163
0.175
0.184
0.259
0.374
0.442
0.447
0.42
0.4
0.394
0.392
0.41
0.403
0.44
0.465
0.467
0.455
0.455
0.456
0.456
0.473
0.471
0.394
0.36
0.532


0.361
0.306
0.315
0.329
0.337
0.363
0.356
0.318
0.318
0.459
0.524
0.288
0.125
0.118
0.125
0.144
0.382
0.661
0.675
0.682
0.686
0.593
0.391
0.42
0.486
0.536
0.61
0.659
0.684
0.688
0.694
0.682
0.667
0.68
0.674
0.663
0.655
0.631
0.581
0.539
0.492
0.437
0.402
0.285
0.185
0.176
0.189
0.309
0.535
0.473
0.283
0.147
0.133
0.255
0.308
0.358
0.448
0.281
0.149
0.118
0.122
0.125
0.124
0.125
0.136
0.226
0.525
0.58
0.615
0.652
0.649
0.617
0.602
0.601
0.567
0.509
0.42
0.397
0.449
0.557
0.569
0.57
0.5
0.423
0.564
0.574
0.597
0.554
0.574
0.324
0.148
0.14
0.136
0.153
0.362
0.381
0.355
0.342
0.352
0.376
0.344
0.297
0.303
0.327
0.325
0.334
0.323
0.291
0.283
0.23
0.246
0.178
0.122
0.118
0.122
0.142
0.369
0.635
0.661
0.67
0.674
0.486
0.381
0.434
0.482
0.515
0.594
0.626
0.657
0.67
0.665
0.667
0.656
0.656
0.662
0.644
0.621
0.549
0.484
0.444
0.435
0.45
0.417
0.377
0.203
0.172
0.189
0.369
0.521
0.44
0.256
0.14
0.142
0.282
0.306
0.338
0.433
0.247
0.127
0.118
0.125
0.122
0.122
0.132
0.156
0.38
0.584
0.602
0.652
0.

0.477
0.467
0.398
0.277
0.24
0.234
0.4
0.504
0.516
0.52
0.518
0.519
0.325
0.11
0.098
0.098
0.113
0.28
0.523
0.541
0.519
0.268
0.216
0.265
0.331
0.391
0.404
0.391
0.353
0.292
0.211
0.23
0.337
0.355
0.424
0.483
0.512
0.525
0.54
0.56
0.545
0.508
0.481
0.48
0.495
0.496
0.456
0.418
0.411
0.415
0.409
0.309
0.267
0.297
0.284
0.283
0.283
0.173
0.108
0.114
0.227
0.579
0.646
0.613
0.618
0.611
0.6
0.61
0.63
0.627
0.608
0.515
0.319
0.26
0.275
0.24
0.175
0.149
0.149
0.194
0.418
0.428
0.425
0.414
0.408
0.413
0.406
0.239
0.188
0.177
0.192
0.185
0.173
0.158
0.362
0.459
0.451
0.461
0.459
0.469
0.471
0.472
0.469
0.379
0.274
0.278
0.455
0.505
0.516
0.518
0.51
0.516
0.326
0.11
0.096
0.098
0.107
0.276
0.531
0.543
0.509
0.273
0.22
0.245
0.312
0.371
0.397
0.4
0.383
0.343
0.28
0.198
0.255
0.351
0.379
0.435
0.477
0.523
0.533
0.55
0.569
0.549
0.504
0.473
0.462
0.467
0.47
0.474
0.442
0.406
0.412
0.396
0.33
0.298
0.29
0.286
0.274
0.144
0.11
0.136
0.416
0.641
0.615
0.592
0.615
0.599
0.586
0.607
0.627
0.626
0.575
0

0.314
0.335
0.328
0.325
0.331
0.328
0.323
0.319
0.324
0.312
0.213
0.158
0.132
0.106
0.11
0.158
0.239
0.265
0.283
0.35
0.425
0.455
0.455
0.445
0.431
0.431
0.434
0.445
0.437
0.431
0.44
0.414
0.333
0.259
0.132
0.109
0.162
0.336
0.424
0.447
0.449
0.452
0.475
0.496
0.496
0.544
0.599
0.616
0.611
0.575
0.497
0.509
0.526
0.354
0.452
0.543
0.568
0.57
0.516
0.386
0.228
0.165
0.188
0.324
0.474
0.468
0.364
0.26
0.204
0.174
0.101
0.135
0.223
0.243
0.243
0.259
0.311
0.357
0.456
0.482
0.456
0.4
0.408
0.408
0.404
0.404
0.397
0.388
0.35
0.203
0.176
0.153
0.165
0.161
0.148
0.114
0.114
0.129
0.162
0.214
0.269
0.312
0.326
0.322
0.314
0.303
0.295
0.299
0.305
0.258
0.169
0.134
0.115
0.098
0.117
0.182
0.248
0.255
0.286
0.384
0.434
0.443
0.455
0.447
0.435
0.431
0.429
0.436
0.435
0.435
0.427
0.419
0.336
0.179
0.106
0.102
0.107
0.171
0.35
0.428
0.448
0.439
0.463
0.493
0.502
0.549
0.607
0.616
0.612
0.582
0.494
0.46
0.616
0.532
0.48
0.569
0.62
0.624
0.613
0.548
0.404
0.212
0.134
0.136
0.222
0.364
0.327
0.252
0.21

In [41]:
for k,x in enumerate(data_2):
    for i in s1:
        if x==i:
            data_2[k]=s111
        else:
            pass

In [42]:
for k,x in enumerate(data_2):
    for i in s2:
        if x==i:
            data_2[k]=s222
        else:
            pass

In [43]:
data_2

array([0.62, 0.62, 0.62, ..., 0.29, 0.29, 0.29])

In [44]:
im_4=data_2.reshape((im_3.shape))

In [45]:
im_4

array([[0.62, 0.62, 0.62, ..., 0.29, 0.29, 0.29],
       [0.62, 0.62, 0.62, ..., 0.29, 0.29, 0.29],
       [0.62, 0.62, 0.62, ..., 0.29, 0.29, 0.29],
       ...,
       [0.29, 0.29, 0.29, ..., 0.29, 0.62, 0.29],
       [0.29, 0.29, 0.29, ..., 0.29, 0.29, 0.29],
       [0.29, 0.29, 0.29, ..., 0.29, 0.29, 0.29]])

In [47]:
cv2.imshow("im_4",im_4)

In [49]:
#cv2.waitKey(0)